platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'AwesomeNewsApp' do
    
    # Networking
    pod 'Alamofire', '~> 4.6.0'
    pod 'AlamofireImage', '~> 3.3'
    pod 'AlamofireObjectMapper', '~> 5.0.0'

    # UI
    pod 'SnapKit', '~> 4.0.0'
    pod 'NVActivityIndicatorView', '~> 4.1.1'
    pod 'Toast-Swift', '~> 3.0.1'
end

target 'AwesomeNewsAppTests' do
    pod 'Alamofire', '~> 4.6.0'
    pod 'AlamofireObjectMapper', '~> 5.0.0'
end
